# Generated by Django 4.2 on 2024-05-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0010_establishment_email"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="establishment",
            index=models.Index(fields=["name"], name="partner_est_name_ab12cf_idx"),
        ),
        migrations.AddIndex(
            model_name="establishment",
            index=models.Index(fields=["owner"], name="partner_est_owner_i_37a288_idx"),
        ),
        migrations.AddIndex(
            model_name="establishment",
            index=models.Index(
                fields=["location"], name="location_gist", opclasses=["gist"]
            ),
        ),
    ]
