# Generated by Django 4.2 on 2024-05-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackanswer",
            name="display_user",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
