# Generated by Django 4.2 on 2024-05-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_order_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-order_date"]},
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["client"], name="order_order_client__f055e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_date"], name="order_order_order_d_721359_idx"
            ),
        ),
    ]
