name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o "StrictHostKeyChecking=no" ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/reviro/backend
            # Pull latest changes
            git pull origin main
#            # Set environment variables
#            export ALLOWED_HOSTS='${{ secrets.ALLOWED_HOSTS }}'
#            export DB_HOST='${{ secrets.DB_HOST }}'
#            export DB_NAME='${{ secrets.DB_NAME }}'
#            export DB_PASSWORD='${{ secrets.DB_PASSWORD }}'
#            export DB_PORT='${{ secrets.DB_PORT }}'
#            export DB_USER='${{ secrets.DB_USER }}'
#            export SECRET_KEY='${{ secrets.SECRET_KEY }}'
            # Use Docker Compose to rebuild and restart the application
            docker-compose down
            docker-compose up --build -d
            # Run migrations
            docker-compose exec web python production-manage.py migrate
          EOF
